name: performance
description: Evaluation of the performance of the rule engine package
# version: 1.0.0
# homepage: https://www.example.com
# author: Pieter Delobelle <pieter.delobelle@gmail.com>

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  rule_engine:
    path: ../../

dev_depende ncies:
  test: ^1.0.0
  lints: ^2.0.0

